const products=[
        {id:'veg',name:'Fresh vegetable basket',category:'Groceries',price:299,tag:'10 min',available:true,img:'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=640&q=80'},
        {id:'rice',name:'Rice, dal and atta monthly pack',category:'Groceries',price:899,tag:'Staples',available:true,img:'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=640&q=80'},
        {id:'fruit',name:'Seasonal fruit box',category:'Groceries',price:349,tag:'Fresh',available:true,img:'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=640&q=80'},
        {id:'milk',name:'Milk, bread and eggs',category:'Groceries',price:189,tag:'Morning',available:true,img:'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=640&q=80'},
        {id:'medicine',name:'Prescription refill pack',category:'Medicines',price:249,tag:'Priority',available:true,img:'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=640&q=80'},
        {id:'firstaid',name:'First-aid emergency kit',category:'Medicines',price:499,tag:'Medic',available:true,img:'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=640&q=80'},
        {id:'meal',name:'Hot meal family combo',category:'Food',price:399,tag:'Fast lane',available:true,img:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=640&q=80'},
        {id:'phone',name:'5G smartphone 128GB',category:'Mobiles',price:18999,tag:'Bestseller',available:true,img:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=640&q=80'},
        {id:'iphone',name:'Premium flagship phone',category:'Mobiles',price:79999,tag:'Notify',available:false,img:'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=640&q=80'},
        {id:'charger',name:'Charger and cable kit',category:'Electronics',price:799,tag:'Same day',available:true,img:'https://images.unsplash.com/photo-1603539444875-76e7684265f6?auto=format&fit=crop&w=640&q=80'},
        {id:'laptop',name:'Student laptop',category:'Electronics',price:45999,tag:'Offer',available:true,img:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=640&q=80'},
        {id:'powerbank',name:'Emergency power bank',category:'Electronics',price:1299,tag:'Power',available:true,img:'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=640&q=80'},
        {id:'kurta',name:'Cotton kurta and daily wear',category:'Fashion',price:999,tag:'New',available:true,img:'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=640&q=80'},
        {id:'shoes',name:'Running shoes',category:'Fashion',price:2199,tag:'Notify',available:false,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=640&q=80'},
        {id:'baby',name:'Baby care essentials',category:'Baby Care',price:549,tag:'Family',available:true,img:'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=640&q=80'},
        {id:'home',name:'Home hygiene pack',category:'Home',price:399,tag:'Monthly',available:true,img:'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=640&q=80'},
        {id:'farm',name:'Farm seed and tool kit',category:'Farm',price:1299,tag:'Rural',available:true,img:'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=640&q=80'},
        {id:'pet',name:'Pet food bundle',category:'Pet Care',price:459,tag:'A-to-Z',available:true,img:'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=640&q=80'}
      ];
      const couponRules={AERO10:{label:'10% off everything',percent:10,categories:[]},GROCERY15:{label:'15% off groceries',percent:15,categories:['Groceries']},MEDIC20:{label:'20% off medicines',percent:20,categories:['Medicines']}};
      let appliedCoupon=null;
      const deliveryAgents={
        'agent-delhi':{name:'Delhi fast agent',type:'Agent',coords:[[28.6139,77.2090],[28.6200,77.2300],[28.6350,77.2500],[28.6500,77.2700]],emoji:'🏍️'},
        'agent-kanpur':{name:'Kanpur Nagar grocery agent',type:'Agent',coords:[[26.4499,80.3319],[26.4550,80.3450],[26.4670,80.3600],[26.4800,80.3750]],emoji:'🏍️'},
        'drone-leh':{name:'Leh remote drone',type:'Drone',coords:[[34.1526,77.5771],[34.1580,77.5900],[34.1680,77.6100],[34.1800,77.6300]],emoji:'🚁'}
      };
      let activeAgentId='agent-kanpur';let liveMap;let liveMarker;let liveRoute;let routeIndex=0;let mapTimer;
      const coverage=['Tier 1: Delhi NCR','Tier 1: Mumbai','Tier 1: Bengaluru','Tier 1: Chennai','Tier 1: Hyderabad','Tier 2: Lucknow','Tier 2: Jaipur','Tier 2: Indore','Tier 2: Patna','Tier 2: Nagpur','Tier 3: Kanpur Nagar','Tier 3: Ranchi','Tier 3: Guwahati','Tier 3: Bhopal','Tier 3: Leh','Rural: Himalayan hamlets','Rural: Desert villages','Rural: Island communities','Rural: Forest belts'];
      const history=[{id:'AS-1007',items:'Groceries + medicines',status:'Delivered',total:948},{id:'AS-1008',items:'Baby care + milk',status:'In transit',total:738},{id:'AS-1009',items:'Drone rural staples',status:'Drone scheduled',total:1598}];
      const kits={monsoon:['medicine','firstaid','powerbank'],rural:['rice','farm','home'],power:['charger','powerbank']};
      let cart=[];let activeCategory='All';let lastTotal=0;
      const rupee=(value)=>`₹${value.toLocaleString('en-IN')}`;const $=(id)=>document.getElementById(id);function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
      function renderProducts(query=''){const filtered=products.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&`${p.name} ${p.category} ${p.tag}`.toLowerCase().includes(query.toLowerCase()));$('productGrid').innerHTML=filtered.map((p,i)=>`<article class="product-card" style="animation-delay:${i*55}ms"><img src="${p.img}" alt="${p.name}"><div class="product-body"><span class="badge ${p.available?'':'out'}">${p.available?'Available now':'Notify when available'}</span><h3>${p.name}</h3><p class="muted">${p.category} with agent, fast, drone, or marketplace shipping.</p><div class="product-meta"><span>${rupee(p.price)}</span><span>⭐ 4.9</span></div><div class="qty-row"><select id="qty-${p.id}" ${p.available?'':'disabled'}><option>1</option><option>2</option><option>3</option><option>4</option></select>${p.available?`<button class="add-btn" data-add="${p.id}">Add to cart</button>`:`<button class="notify-btn" data-notify="${p.id}">Notify me</button>`}</div></div></article>`).join('')||'<div class="empty">No items found. Try another search.</div>'}
      function renderFilters(){const cats=['All',...new Set(products.map(p=>p.category))];$('categoryFilters').innerHTML=cats.map(c=>`<button class="chip ${c===activeCategory?'active':''}" data-category="${c}">${c}</button>`).join('')}
      function discountAmount(subtotal){if(!appliedCoupon||!couponRules[appliedCoupon])return 0;const rule=couponRules[appliedCoupon];const eligible=rule.categories.length?cart.filter(i=>rule.categories.includes(i.category)).reduce((s,i)=>s+i.qty*i.price,0):subtotal;return Math.round(eligible*rule.percent/100)}function renderCart(){const count=cart.reduce((s,i)=>s+i.qty,0);const subtotal=cart.reduce((s,i)=>s+i.qty*i.price,0);const discount=discountAmount(subtotal);const fee=subtotal?29:0;lastTotal=Math.max(subtotal-discount+fee,0);$('cartCount').textContent=count;$('subtotal').textContent=rupee(subtotal);$('discount').textContent=`-${rupee(discount)}`;$('deliveryFee').textContent=rupee(fee);$('grandTotal').textContent=rupee(lastTotal);$('cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><img src="${i.img}" alt="${i.name}"><div><b>${i.name}</b><br><small>${rupee(i.price)} × ${i.qty}</small></div><div class="cart-controls"><button class="tiny-btn" data-dec="${i.id}">−</button><b>${i.qty}</b><button class="tiny-btn" data-inc="${i.id}">+</button></div></div>`).join(''):'<div class="empty">Your cart is empty. Add groceries, medicines, mobiles, electronics, fashion, or home items.</div>'}
      function renderOrders(){$('ordersGrid').innerHTML=history.map(o=>`<article class="order-card"><h3>${o.id}<span class="status">${o.status}</span></h3><p class="muted">${o.items}</p><div class="total-line"><span>Total</span><span>${rupee(o.total)}</span></div><button class="ghost-btn" data-reorder="${o.id}">Reorder</button></article>`).join('')}
      
      function initLiveMap(){if(!window.L){$('mapStatus').textContent='Map API could not load. Tracking fallback is active for Kanpur Nagar.';return}const agent=deliveryAgents[activeAgentId];liveMap=L.map('liveMap',{scrollWheelZoom:false}).setView([22.9734,78.6569],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(liveMap);liveRoute=L.polyline(agent.coords,{color:'#16a34a',weight:5,opacity:.8}).addTo(liveMap);liveMarker=L.marker(agent.coords[0]).addTo(liveMap);startAgentTracking(activeAgentId)}
      function startAgentTracking(agentId){activeAgentId=agentId;routeIndex=0;const agent=deliveryAgents[agentId];if(!agent)return;if(mapTimer)clearInterval(mapTimer);if(liveMap&&window.L){if(liveRoute)liveMap.removeLayer(liveRoute);liveRoute=L.polyline(agent.coords,{color:agent.type==='Drone'?'#2563eb':'#16a34a',weight:5,opacity:.85}).addTo(liveMap);if(!liveMarker)liveMarker=L.marker(agent.coords[0]).addTo(liveMap);liveMap.setView(agent.coords[0],12)}function tick(){const point=agent.coords[routeIndex%agent.coords.length];if(liveMarker)liveMarker.setLatLng(point).bindPopup(`${agent.emoji} ${agent.name}<br>Live: ${point[0].toFixed(4)}, ${point[1].toFixed(4)}`).openPopup();$('mapStatus').textContent=`${agent.emoji} ${agent.name} live at ${point[0].toFixed(4)}, ${point[1].toFixed(4)} • ETA ${12-routeIndex*2>4?12-routeIndex*2:4} min`;routeIndex++;}tick();mapTimer=setInterval(tick,2200)}
      function locateUser(){if(!navigator.geolocation){toast('Geolocation is not available in this browser');return}navigator.geolocation.getCurrentPosition((pos)=>{const point=[pos.coords.latitude,pos.coords.longitude];if(liveMap&&window.L){L.marker(point).addTo(liveMap).bindPopup('📍 Your location').openPopup();liveMap.setView(point,13)}toast('Your location added to the map')},()=>toast('Location permission denied or unavailable'))}
      function addToCart(id,qty=1){const p=products.find(x=>x.id===id);if(!p.available){toast(`${p.name} is unavailable. Notification enabled.`);return}const item=cart.find(x=>x.id===id);item?item.qty+=qty:cart.push({...p,qty});renderCart();toast(`${p.name} added to cart ✅`)}function applyCoupon(code){const normalized=code.trim().toUpperCase();if(!couponRules[normalized]){toast('Invalid coupon. Try AERO10, GROCERY15, or MEDIC20');return}appliedCoupon=normalized;$('couponInput').value=normalized;renderCart();toast(`${normalized} applied: ${couponRules[normalized].label}`)}function placeOrder(paymentId='demo_cod'){const total=lastTotal;history.unshift({id:`AS-${1010+history.length}`,items:cart.map(i=>i.name).slice(0,2).join(' + '),status:`Paid: ${paymentId}`,total});cart=[];renderCart();renderOrders();$('orders').scrollIntoView({behavior:'smooth'});toast('Order placed successfully 🚀')}function openRazorpayCheckout(){if(!cart.length){toast('Add items before payment');return}if(!window.Razorpay){toast('Razorpay SDK unavailable. Demo order placed.');placeOrder();return}const options={key:'rzp_test_REPLACE_WITH_KEY_ID',amount:lastTotal*100,currency:'INR',name:'AeroSell',description:'AI commerce basket',image:'',prefill:{name:'Hackathon Demo User',email:'demo@aerosell.ai',contact:'9999999999'},notes:{platform:'AeroSell AI Builder Hackathon demo',coupon:appliedCoupon||'none'},theme:{color:'#16a34a'},handler:(response)=>placeOrder(response.razorpay_payment_id||'razorpay_success'),modal:{ondismiss:()=>toast('Razorpay payment cancelled')}};new Razorpay(options).open()}
      renderProducts();renderFilters();renderCart();renderOrders();$('coverageList').innerHTML=coverage.map(c=>`<span>${c}</span>`).join('');initLiveMap();if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
      document.addEventListener('click',(e)=>{const scroll=e.target.closest('[data-scroll]');if(scroll){$(scroll.dataset.scroll).scrollIntoView({behavior:'smooth'});return}const add=e.target.closest('[data-add]');if(add){addToCart(add.dataset.add,Number($(`qty-${add.dataset.add}`).value));return}const notify=e.target.closest('[data-notify]');if(notify){const p=products.find(x=>x.id===notify.dataset.notify);toast(`We will notify you when ${p.name} is available`);return}const inc=e.target.closest('[data-inc]');if(inc){addToCart(inc.dataset.inc);return}const dec=e.target.closest('[data-dec]');if(dec){const item=cart.find(i=>i.id===dec.dataset.dec);if(item){item.qty--;if(item.qty<=0)cart=cart.filter(i=>i.id!==item.id);renderCart();toast('Cart updated')}}const cat=e.target.closest('[data-category]');if(cat){activeCategory=cat.dataset.category;renderFilters();renderProducts($('needSearch').value)}const agentBtn=e.target.closest('[data-agent]');if(agentBtn){startAgentTracking(agentBtn.dataset.agent);return}const coupon=e.target.closest('[data-coupon]');if(coupon){applyCoupon(coupon.dataset.coupon);return}const kit=e.target.closest('[data-kit]');if(kit){kits[kit.dataset.kit].forEach(id=>addToCart(id));$('cart').scrollIntoView({behavior:'smooth'})}const reorder=e.target.closest('[data-reorder]');if(reorder){addToCart('veg');addToCart('medicine');$('cart').scrollIntoView({behavior:'smooth'});toast(`${reorder.dataset.reorder} added again`)}});
      $('needSearch').addEventListener('input',e=>renderProducts(e.target.value));$('searchForm').addEventListener('submit',e=>{e.preventDefault();$('shop').scrollIntoView({behavior:'smooth'});toast('Showing matching items')});$('checkoutBtn').addEventListener('click',openRazorpayCheckout);$('applyCouponBtn').addEventListener('click',()=>applyCoupon($('couponInput').value));$('clearCartBtn').addEventListener('click',()=>{cart=[];renderCart();toast('Cart cleared')});$('emergencyCallBtn').addEventListener('click',()=>$('emergency').scrollIntoView({behavior:'smooth'}));$('locateUserBtn').addEventListener('click',locateUser);$('panicBtn').addEventListener('click',()=>toast('Emergency request started. Call 1800-123-AERO now.'));
